// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all procedure arg schemas
import * as CheckSchemeStatusProcedure from "../check_scheme_status_procedure";
import * as FetchMandiPricesProcedure from "../fetch_mandi_prices_procedure";
import * as TranscribeVoiceNoteProcedure from "../transcribe_voice_note_procedure";

export type CheckSchemeStatusArgs = __Infer<typeof CheckSchemeStatusProcedure.params>;
export type CheckSchemeStatusResult = __Infer<typeof CheckSchemeStatusProcedure.returnType>;
export type FetchMandiPricesArgs = __Infer<typeof FetchMandiPricesProcedure.params>;
export type FetchMandiPricesResult = __Infer<typeof FetchMandiPricesProcedure.returnType>;
export type TranscribeVoiceNoteArgs = __Infer<typeof TranscribeVoiceNoteProcedure.params>;
export type TranscribeVoiceNoteResult = __Infer<typeof TranscribeVoiceNoteProcedure.returnType>;

