// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AddCurriculumItemReducer from "../add_curriculum_item_reducer";
import DismissMemoryReducer from "../dismiss_memory_reducer";
import LogActivityReducer from "../log_activity_reducer";
import RecordCropEventReducer from "../record_crop_event_reducer";
import RecordMoneyEventReducer from "../record_money_event_reducer";
import RegisterFarmerReducer from "../register_farmer_reducer";
import RemoveMoneyEventReducer from "../remove_money_event_reducer";
import SaveChatMessageReducer from "../save_chat_message_reducer";
import SaveMemoryReducer from "../save_memory_reducer";
import StoreDocumentReducer from "../store_document_reducer";
import UpdateCurriculumStatusReducer from "../update_curriculum_status_reducer";
import UpdateDocumentOcrReducer from "../update_document_ocr_reducer";
import UpdateFarmerContextReducer from "../update_farmer_context_reducer";
import UpdateLearningProfileReducer from "../update_learning_profile_reducer";
import UpdateMarketPricesReducer from "../update_market_prices_reducer";
import UpdateMoneyEventReducer from "../update_money_event_reducer";
import UpdateSchemeStatusReducer from "../update_scheme_status_reducer";
import UpsertPartyReducer from "../upsert_party_reducer";

export type AddCurriculumItemParams = __Infer<typeof AddCurriculumItemReducer>;
export type DismissMemoryParams = __Infer<typeof DismissMemoryReducer>;
export type LogActivityParams = __Infer<typeof LogActivityReducer>;
export type RecordCropEventParams = __Infer<typeof RecordCropEventReducer>;
export type RecordMoneyEventParams = __Infer<typeof RecordMoneyEventReducer>;
export type RegisterFarmerParams = __Infer<typeof RegisterFarmerReducer>;
export type RemoveMoneyEventParams = __Infer<typeof RemoveMoneyEventReducer>;
export type SaveChatMessageParams = __Infer<typeof SaveChatMessageReducer>;
export type SaveMemoryParams = __Infer<typeof SaveMemoryReducer>;
export type StoreDocumentParams = __Infer<typeof StoreDocumentReducer>;
export type UpdateCurriculumStatusParams = __Infer<typeof UpdateCurriculumStatusReducer>;
export type UpdateDocumentOcrParams = __Infer<typeof UpdateDocumentOcrReducer>;
export type UpdateFarmerContextParams = __Infer<typeof UpdateFarmerContextReducer>;
export type UpdateLearningProfileParams = __Infer<typeof UpdateLearningProfileReducer>;
export type UpdateMarketPricesParams = __Infer<typeof UpdateMarketPricesReducer>;
export type UpdateMoneyEventParams = __Infer<typeof UpdateMoneyEventReducer>;
export type UpdateSchemeStatusParams = __Infer<typeof UpdateSchemeStatusReducer>;
export type UpsertPartyParams = __Infer<typeof UpsertPartyReducer>;

