// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  farmerId: __t.identity().name("farmer_id"),
  kind: __t.string(),
  crop: __t.string(),
  plotId: __t.string().name("plot_id"),
  photoBytes: __t.option(__t.byteArray()).name("photo_bytes"),
  aiNotes: __t.string().name("ai_notes"),
  gpsLat: __t.option(__t.f64()).name("gps_lat"),
  gpsLon: __t.option(__t.f64()).name("gps_lon"),
  createdAt: __t.timestamp().name("created_at"),
});
