// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  farmerId: __t.identity().name("farmer_id"),
  kind: __t.string(),
  bytes: __t.byteArray(),
  ocrText: __t.string().name("ocr_text"),
  structuredJson: __t.string().name("structured_json"),
  hotColdState: __t.string().name("hot_cold_state"),
  createdAt: __t.timestamp().name("created_at"),
});
