// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  farmerId: __t.identity().primaryKey().name("farmer_id"),
  crops: __t.string(),
  acres: __t.u32(),
  plots: __t.string(),
  irrigationType: __t.string().name("irrigation_type"),
  seasonStage: __t.string().name("season_stage"),
  painPoints: __t.string().name("pain_points"),
  rawStoryJson: __t.string().name("raw_story_json"),
});
