// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  farmerId: __t.identity().name("farmer_id"),
  content: __t.string(),
  source: __t.string(),
  confidence: __t.f64(),
  active: __t.bool(),
  createdAt: __t.timestamp().name("created_at"),
  lastUsedAt: __t.timestamp().name("last_used_at"),
});
