// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
// MANUAL FIX (2026-03-17): Added `accessor` field to every index definition.
// The codegen (CLI 2.0.3) omits it but SDK v2.0.4 requires a non-empty accessor.

// This was generated using spacetimedb cli version 2.0.3 (commit 5836c268a7307f864b33636357b0869ecc40bc0a).

/* eslint-disable */
/* tslint:disable */
import {
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TypeBuilder as __TypeBuilder,
  Uuid as __Uuid,
  convertToAccessorMap as __convertToAccessorMap,
  makeQueryBuilder as __makeQueryBuilder,
  procedureSchema as __procedureSchema,
  procedures as __procedures,
  reducerSchema as __reducerSchema,
  reducers as __reducers,
  schema as __schema,
  t as __t,
  table as __table,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type DbConnectionConfig as __DbConnectionConfig,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type Infer as __Infer,
  type QueryBuilder as __QueryBuilder,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type RemoteModule as __RemoteModule,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type SubscriptionHandleImpl as __SubscriptionHandleImpl,
} from "spacetimedb";

// Import all reducer arg schemas
import AddCurriculumItemReducer from "./add_curriculum_item_reducer";
import DismissMemoryReducer from "./dismiss_memory_reducer";
import LogActivityReducer from "./log_activity_reducer";
import RecordCropEventReducer from "./record_crop_event_reducer";
import RecordMoneyEventReducer from "./record_money_event_reducer";
import RegisterFarmerReducer from "./register_farmer_reducer";
import RemoveMoneyEventReducer from "./remove_money_event_reducer";
import SaveChatMessageReducer from "./save_chat_message_reducer";
import SaveMemoryReducer from "./save_memory_reducer";
import StoreDocumentReducer from "./store_document_reducer";
import UpdateCurriculumStatusReducer from "./update_curriculum_status_reducer";
import UpdateDocumentOcrReducer from "./update_document_ocr_reducer";
import UpdateFarmerContextReducer from "./update_farmer_context_reducer";
import UpdateLearningProfileReducer from "./update_learning_profile_reducer";
import UpdateMarketPricesReducer from "./update_market_prices_reducer";
import UpdateMoneyEventReducer from "./update_money_event_reducer";
import UpdateSchemeStatusReducer from "./update_scheme_status_reducer";
import UpsertPartyReducer from "./upsert_party_reducer";

// Import all procedure arg schemas
import * as CheckSchemeStatusProcedure from "./check_scheme_status_procedure";
import * as FetchMandiPricesProcedure from "./fetch_mandi_prices_procedure";
import * as TranscribeVoiceNoteProcedure from "./transcribe_voice_note_procedure";

// Import all table schema definitions
import ActivityLogRow from "./activity_log_table";
import ChatMessageRow from "./chat_message_table";
import CropEventRow from "./crop_event_table";
import CurriculumItemRow from "./curriculum_item_table";
import DocumentRow from "./document_table";
import FarmerRow from "./farmer_table";
import FarmerContextRow from "./farmer_context_table";
import FarmerMemoryRow from "./farmer_memory_table";
import FarmerBalanceRow from "./farmer_balance_table";
import LearningProfileRow from "./learning_profile_table";
import MarketPriceRow from "./market_price_table";
import MoneyEventRow from "./money_event_table";
import PartyRow from "./party_table";
import SchemeStatusRow from "./scheme_status_table";

/** Type-only namespace exports for generated type groups. */

/** The schema information for all tables in this module. This is defined the same was as the tables would have been defined in the server. */
const tablesSchema = __schema({
  activityLog: __table({
    name: 'activity_log',
    indexes: [
      { name: 'activity_log_farmer_id', accessor: 'activity_log_farmer_id', algorithm: 'btree', columns: [
        'farmerId',
      ] },
      { name: 'id', accessor: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'activity_log_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ActivityLogRow),
  chatMessage: __table({
    name: 'chat_message',
    indexes: [
      { name: 'chat_message_farmer_id', accessor: 'chat_message_farmer_id', algorithm: 'btree', columns: [
        'farmerId',
      ] },
      { name: 'id', accessor: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'chat_message_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ChatMessageRow),
  cropEvent: __table({
    name: 'crop_event',
    indexes: [
      { name: 'crop_event_farmer_id', accessor: 'crop_event_farmer_id', algorithm: 'btree', columns: [
        'farmerId',
      ] },
      { name: 'id', accessor: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'crop_event_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, CropEventRow),
  curriculumItem: __table({
    name: 'curriculum_item',
    indexes: [
      { name: 'curriculum_item_farmer_id', accessor: 'curriculum_item_farmer_id', algorithm: 'btree', columns: [
        'farmerId',
      ] },
      { name: 'id', accessor: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'curriculum_item_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, CurriculumItemRow),
  document: __table({
    name: 'document',
    indexes: [
      { name: 'document_farmer_id', accessor: 'document_farmer_id', algorithm: 'btree', columns: [
        'farmerId',
      ] },
      { name: 'id', accessor: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'document_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, DocumentRow),
  farmer: __table({
    name: 'farmer',
    indexes: [
      { name: 'identity', accessor: 'identity', algorithm: 'btree', columns: [
        'identity',
      ] },
    ],
    constraints: [
      { name: 'farmer_identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, FarmerRow),
  farmerContext: __table({
    name: 'farmer_context',
    indexes: [
      { name: 'farmer_id', accessor: 'farmer_id', algorithm: 'btree', columns: [
        'farmerId',
      ] },
    ],
    constraints: [
      { name: 'farmer_context_farmer_id_key', constraint: 'unique', columns: ['farmerId'] },
    ],
  }, FarmerContextRow),
  farmerMemory: __table({
    name: 'farmer_memory',
    indexes: [
      { name: 'farmer_memory_farmer_id', accessor: 'farmer_memory_farmer_id', algorithm: 'btree', columns: [
        'farmerId',
      ] },
      { name: 'id', accessor: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'farmer_memory_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, FarmerMemoryRow),
  learningProfile: __table({
    name: 'learning_profile',
    indexes: [
      { name: 'farmer_id', accessor: 'farmer_id', algorithm: 'btree', columns: [
        'farmerId',
      ] },
    ],
    constraints: [
      { name: 'learning_profile_farmer_id_key', constraint: 'unique', columns: ['farmerId'] },
    ],
  }, LearningProfileRow),
  marketPrice: __table({
    name: 'market_price',
    indexes: [
      { name: 'market_price_crop', accessor: 'market_price_crop', algorithm: 'btree', columns: [
        'crop',
      ] },
      { name: 'market_price_district', accessor: 'market_price_district', algorithm: 'btree', columns: [
        'district',
      ] },
      { name: 'id', accessor: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'market_price_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, MarketPriceRow),
  moneyEvent: __table({
    name: 'money_event',
    indexes: [
      { name: 'money_event_farmer_id', accessor: 'money_event_farmer_id', algorithm: 'btree', columns: [
        'farmerId',
      ] },
      { name: 'id', accessor: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'idempotency_key', accessor: 'idempotency_key', algorithm: 'btree', columns: [
        'idempotencyKey',
      ] },
    ],
    constraints: [
      { name: 'money_event_id_key', constraint: 'unique', columns: ['id'] },
      { name: 'money_event_idempotency_key_key', constraint: 'unique', columns: ['idempotencyKey'] },
    ],
  }, MoneyEventRow),
  party: __table({
    name: 'party',
    indexes: [
      { name: 'party_farmer_id', accessor: 'party_farmer_id', algorithm: 'btree', columns: [
        'farmerId',
      ] },
      { name: 'id', accessor: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'party_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, PartyRow),
  schemeStatus: __table({
    name: 'scheme_status',
    indexes: [
      { name: 'scheme_status_farmer_id', accessor: 'scheme_status_farmer_id', algorithm: 'btree', columns: [
        'farmerId',
      ] },
      { name: 'id', accessor: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'scheme_status_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, SchemeStatusRow),
  farmer_balance: __table({
    name: 'farmer_balance',
    indexes: [
    ],
    constraints: [
    ],
  }, FarmerBalanceRow),
});

/** The schema information for all reducers in this module. This is defined the same way as the reducers would have been defined in the server, except the body of the reducer is omitted in code generation. */
const reducersSchema = __reducers(
  __reducerSchema("add_curriculum_item", AddCurriculumItemReducer),
  __reducerSchema("dismiss_memory", DismissMemoryReducer),
  __reducerSchema("log_activity", LogActivityReducer),
  __reducerSchema("record_crop_event", RecordCropEventReducer),
  __reducerSchema("record_money_event", RecordMoneyEventReducer),
  __reducerSchema("register_farmer", RegisterFarmerReducer),
  __reducerSchema("remove_money_event", RemoveMoneyEventReducer),
  __reducerSchema("save_chat_message", SaveChatMessageReducer),
  __reducerSchema("save_memory", SaveMemoryReducer),
  __reducerSchema("store_document", StoreDocumentReducer),
  __reducerSchema("update_curriculum_status", UpdateCurriculumStatusReducer),
  __reducerSchema("update_document_ocr", UpdateDocumentOcrReducer),
  __reducerSchema("update_farmer_context", UpdateFarmerContextReducer),
  __reducerSchema("update_learning_profile", UpdateLearningProfileReducer),
  __reducerSchema("update_market_prices", UpdateMarketPricesReducer),
  __reducerSchema("update_money_event", UpdateMoneyEventReducer),
  __reducerSchema("update_scheme_status", UpdateSchemeStatusReducer),
  __reducerSchema("upsert_party", UpsertPartyReducer),
);

/** The schema information for all procedures in this module. This is defined the same way as the procedures would have been defined in the server. */
const proceduresSchema = __procedures(
  __procedureSchema("check_scheme_status", CheckSchemeStatusProcedure.params, CheckSchemeStatusProcedure.returnType),
  __procedureSchema("fetch_mandi_prices", FetchMandiPricesProcedure.params, FetchMandiPricesProcedure.returnType),
  __procedureSchema("transcribe_voice_note", TranscribeVoiceNoteProcedure.params, TranscribeVoiceNoteProcedure.returnType),
);

/** The remote SpacetimeDB module schema, both runtime and type information. */
const REMOTE_MODULE = {
  versionInfo: {
    cliVersion: "2.0.3" as const,
  },
  tables: tablesSchema.schemaType.tables,
  reducers: reducersSchema.reducersType.reducers,
  ...proceduresSchema,
} satisfies __RemoteModule<
  typeof tablesSchema.schemaType,
  typeof reducersSchema.reducersType,
  typeof proceduresSchema
>;

/** The tables available in this remote SpacetimeDB module. Each table reference doubles as a query builder. */
export const tables: __QueryBuilder<typeof tablesSchema.schemaType> = __makeQueryBuilder(tablesSchema.schemaType);

/** The reducers available in this remote SpacetimeDB module. */
export const reducers = __convertToAccessorMap(reducersSchema.reducersType.reducers);

/** The context type returned in callbacks for all possible events. */
export type EventContext = __EventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for reducer events. */
export type ReducerEventContext = __ReducerEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for subscription events. */
export type SubscriptionEventContext = __SubscriptionEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for error events. */
export type ErrorContext = __ErrorContextInterface<typeof REMOTE_MODULE>;
/** The subscription handle type to manage active subscriptions created from a {@link SubscriptionBuilder}. */
export type SubscriptionHandle = __SubscriptionHandleImpl<typeof REMOTE_MODULE>;

/** Builder class to configure a new subscription to the remote SpacetimeDB instance. */
export class SubscriptionBuilder extends __SubscriptionBuilderImpl<typeof REMOTE_MODULE> {}

/** Builder class to configure a new database connection to the remote SpacetimeDB instance. */
export class DbConnectionBuilder extends __DbConnectionBuilder<DbConnection> {}

/** The typed database connection to manage connections to the remote SpacetimeDB instance. This class has type information specific to the generated module. */
export class DbConnection extends __DbConnectionImpl<typeof REMOTE_MODULE> {
  /** Creates a new {@link DbConnectionBuilder} to configure and connect to the remote SpacetimeDB instance. */
  static builder = (): DbConnectionBuilder => {
    return new DbConnectionBuilder(REMOTE_MODULE, (config: __DbConnectionConfig<typeof REMOTE_MODULE>) => new DbConnection(config));
  };

  /** Creates a new {@link SubscriptionBuilder} to configure a subscription to the remote SpacetimeDB instance. */
  override subscriptionBuilder = (): SubscriptionBuilder => {
    return new SubscriptionBuilder(this);
  };
}

