// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  farmerId: __t.identity().primaryKey().name("farmer_id"),
  literacyLevel: __t.string().name("literacy_level"),
  preferredMode: __t.string().name("preferred_mode"),
  pace: __t.string(),
  topicsNeededJson: __t.string().name("topics_needed_json"),
  lastUpdated: __t.timestamp().name("last_updated"),
});
