// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  crop: __t.string(),
  mandi: __t.string(),
  district: __t.string(),
  pricePerQuintalPaise: __t.u64().name("price_per_quintal_paise"),
  mspPricePaise: __t.u64().name("msp_price_paise"),
  date: __t.string(),
});
