// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  farmerId: __t.identity().name("farmer_id"),
  kind: __t.string(),
  amountPaise: __t.u64().name("amount_paise"),
  isIncome: __t.bool().name("is_income"),
  category: __t.string(),
  description: __t.string(),
  partyName: __t.string().name("party_name"),
  season: __t.string(),
  idempotencyKey: __t.string().name("idempotency_key"),
  createdAt: __t.timestamp().name("created_at"),
});
