// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  kind: __t.string(),
  crop: __t.string(),
  plotId: __t.string(),
  photoBytes: __t.option(__t.byteArray()),
  aiNotes: __t.string(),
  gpsLat: __t.option(__t.f64()),
  gpsLon: __t.option(__t.f64()),
};
