// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  farmerId: __t.identity().name("farmer_id"),
  schemeName: __t.string().name("scheme_name"),
  status: __t.string(),
  lastChecked: __t.timestamp().name("last_checked"),
  amountPaise: __t.u64().name("amount_paise"),
  detailsJson: __t.string().name("details_json"),
});
