// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const ActivityLog = __t.object("ActivityLog", {
  id: __t.u64(),
  farmerId: __t.identity(),
  entityType: __t.string(),
  action: __t.string(),
  detail: __t.string(),
  createdAt: __t.timestamp(),
});
export type ActivityLog = __Infer<typeof ActivityLog>;

export const ChatMessage = __t.object("ChatMessage", {
  id: __t.u64(),
  farmerId: __t.identity(),
  role: __t.string(),
  content: __t.string(),
  intent: __t.string(),
  metadataJson: __t.string(),
  createdAt: __t.timestamp(),
});
export type ChatMessage = __Infer<typeof ChatMessage>;

export const CropEvent = __t.object("CropEvent", {
  id: __t.u64(),
  farmerId: __t.identity(),
  kind: __t.string(),
  crop: __t.string(),
  plotId: __t.string(),
  photoBytes: __t.option(__t.byteArray()),
  aiNotes: __t.string(),
  gpsLat: __t.option(__t.f64()),
  gpsLon: __t.option(__t.f64()),
  createdAt: __t.timestamp(),
});
export type CropEvent = __Infer<typeof CropEvent>;

export const CurriculumItem = __t.object("CurriculumItem", {
  id: __t.u64(),
  farmerId: __t.identity(),
  topic: __t.string(),
  stage: __t.string(),
  contentTe: __t.string(),
  sourceUrl: __t.string(),
  citationsJson: __t.string(),
  status: __t.string(),
  createdAt: __t.timestamp(),
});
export type CurriculumItem = __Infer<typeof CurriculumItem>;

export const Document = __t.object("Document", {
  id: __t.u64(),
  farmerId: __t.identity(),
  kind: __t.string(),
  bytes: __t.byteArray(),
  ocrText: __t.string(),
  structuredJson: __t.string(),
  hotColdState: __t.string(),
  createdAt: __t.timestamp(),
});
export type Document = __Infer<typeof Document>;

export const Farmer = __t.object("Farmer", {
  identity: __t.identity(),
  name: __t.string(),
  phone: __t.string(),
  village: __t.string(),
  district: __t.string(),
  language: __t.string(),
  literacyLevel: __t.string(),
  createdAt: __t.timestamp(),
});
export type Farmer = __Infer<typeof Farmer>;

export const FarmerBalance = __t.object("FarmerBalance", {});
export type FarmerBalance = __Infer<typeof FarmerBalance>;

export const FarmerBalanceRow = __t.object("FarmerBalanceRow", {
  farmerId: __t.identity(),
  totalIncomePaise: __t.u64(),
  totalExpensePaise: __t.u64(),
});
export type FarmerBalanceRow = __Infer<typeof FarmerBalanceRow>;

export const FarmerContext = __t.object("FarmerContext", {
  farmerId: __t.identity(),
  crops: __t.string(),
  acres: __t.u32(),
  plots: __t.string(),
  irrigationType: __t.string(),
  seasonStage: __t.string(),
  painPoints: __t.string(),
  rawStoryJson: __t.string(),
});
export type FarmerContext = __Infer<typeof FarmerContext>;

export const FarmerMemory = __t.object("FarmerMemory", {
  id: __t.u64(),
  farmerId: __t.identity(),
  content: __t.string(),
  source: __t.string(),
  confidence: __t.f64(),
  active: __t.bool(),
  createdAt: __t.timestamp(),
  lastUsedAt: __t.timestamp(),
});
export type FarmerMemory = __Infer<typeof FarmerMemory>;

export const LearningProfile = __t.object("LearningProfile", {
  farmerId: __t.identity(),
  literacyLevel: __t.string(),
  preferredMode: __t.string(),
  pace: __t.string(),
  topicsNeededJson: __t.string(),
  lastUpdated: __t.timestamp(),
});
export type LearningProfile = __Infer<typeof LearningProfile>;

export const MarketPrice = __t.object("MarketPrice", {
  id: __t.u64(),
  crop: __t.string(),
  mandi: __t.string(),
  district: __t.string(),
  pricePerQuintalPaise: __t.u64(),
  mspPricePaise: __t.u64(),
  date: __t.string(),
});
export type MarketPrice = __Infer<typeof MarketPrice>;

export const MarketPriceInput = __t.object("MarketPriceInput", {
  crop: __t.string(),
  mandi: __t.string(),
  district: __t.string(),
  pricePaise: __t.u64(),
  mspPaise: __t.u64(),
  date: __t.string(),
});
export type MarketPriceInput = __Infer<typeof MarketPriceInput>;

export const MoneyEvent = __t.object("MoneyEvent", {
  id: __t.u64(),
  farmerId: __t.identity(),
  kind: __t.string(),
  amountPaise: __t.u64(),
  isIncome: __t.bool(),
  category: __t.string(),
  description: __t.string(),
  partyName: __t.string(),
  season: __t.string(),
  idempotencyKey: __t.string(),
  createdAt: __t.timestamp(),
});
export type MoneyEvent = __Infer<typeof MoneyEvent>;

export const Party = __t.object("Party", {
  id: __t.u64(),
  farmerId: __t.identity(),
  name: __t.string(),
  kind: __t.string(),
  phone: __t.string(),
  isDealer: __t.bool(),
  isBuyer: __t.bool(),
  grade: __t.string(),
});
export type Party = __Infer<typeof Party>;

export const SchemeStatus = __t.object("SchemeStatus", {
  id: __t.u64(),
  farmerId: __t.identity(),
  schemeName: __t.string(),
  status: __t.string(),
  lastChecked: __t.timestamp(),
  amountPaise: __t.u64(),
  detailsJson: __t.string(),
});
export type SchemeStatus = __Infer<typeof SchemeStatus>;

